"""Trusted, versioned capability packages available to company agents."""

BUILTIN_SKILLS = [
    {
        "id": "market-evidence",
        "name": "Market Evidence",
        "version": "1.0.0",
        "roles": ["research"],
        "actions": ["research_market"],
        "tools": ["web_search"],
        "permissions": ["read_public_web"],
        "instructions": "Separate facts, inference and assumptions. Use at least two direct sources and fail closed when evidence is weak.",
        "success": ["Two verifiable URLs", "Claims linked to evidence", "Unknowns explicit"],
    },
    {
        "id": "build-buy-integrate",
        "name": "Build / Buy / Integrate",
        "version": "1.0.0",
        "roles": ["platform", "ceo"],
        "actions": ["evaluate_platform", "request_platform_access", "discover_tool"],
        "tools": ["web_search"],
        "permissions": ["read_public_web"],
        "instructions": "Compare build, buy, integrate and manual validation on cost, time, lock-in, API access and reversibility.",
        "success": [
            "All four paths compared",
            "Total cost considered",
            "One reversible recommendation",
        ],
    },
    {
        "id": "lean-product",
        "name": "Lean Product Definition",
        "version": "1.0.0",
        "roles": ["product", "development"],
        "actions": ["define_product", "build_mvp"],
        "tools": ["workspace"],
        "permissions": ["write_workspace"],
        "instructions": "Define the smallest testable workflow, explicit non-goals, acceptance criteria and a measurable demand hypothesis.",
        "success": ["Narrow ICP", "Acceptance criteria", "Non-goals", "Validation metric"],
    },
    {
        "id": "quality-gate",
        "name": "Adversarial Quality Gate",
        "version": "1.0.0",
        "roles": ["qa"],
        "actions": ["qa_mvp"],
        "tools": ["workspace", "tests"],
        "permissions": ["read_workspace", "run_tests"],
        "instructions": "Try to falsify readiness. Report reproducible failures, risks and a clear go/no-go recommendation.",
        "success": ["Reproducible checks", "Risk severity", "Go/no-go"],
    },
    {
        "id": "outreach-preparation",
        "name": "Outreach Preparation",
        "version": "1.0.0",
        "roles": ["growth"],
        "actions": ["prepare_outreach"],
        "tools": ["web_search"],
        "permissions": ["read_public_web"],
        "instructions": "Research targets and prepare drafts only. Never transmit a message, fabricate contact data or claim outreach occurred.",
        "success": ["Ranked targets", "Personalization evidence", "Drafts clearly unsent"],
    },
    {
        "id": "content-seo",
        "name": "Content & SEO Workflow",
        "version": "1.0.0",
        "roles": ["research", "growth", "operations"],
        "actions": [
            "research_content",
            "create_content_draft",
            "save_content_draft",
            "publish_content",
        ],
        "tools": ["web_search", "workspace", "browser"],
        "permissions": ["read_public_web", "write_workspace", "browser_bounded"],
        "instructions": "Research intent and authoritative sources, create one reviewable content artifact, save only an unpublished platform draft, and reserve publication for one explicit owner decision.",
        "success": [
            "Demand and intent rationale",
            "Authoritative sources",
            "Complete SEO draft",
            "Publication separated from drafting",
        ],
    },
    {
        "id": "safe-browser-ops",
        "name": "Safe Browser Operations",
        "version": "1.0.0",
        "roles": ["operations"],
        "actions": ["browser_operate", "request_human_handoff"],
        "tools": ["browser"],
        "permissions": ["browser_bounded"],
        "instructions": "Use explicit domains and success evidence. Stop for CAPTCHA, login ownership, 2FA, identity, terms or payment checkpoints.",
        "success": ["Bounded domain", "Audited steps", "Human checkpoint respected"],
    },
    {
        "id": "ecommerce-platform-ops",
        "name": "Ecommerce Platform Operations",
        "version": "1.0.0",
        "roles": ["platform", "operations", "growth"],
        "actions": [
            "evaluate_platform",
            "request_platform_access",
            "source_products",
            "publish_catalog",
        ],
        "tools": ["web_search", "platform_api"],
        "permissions": ["read_public_web"],
        "instructions": "Prefer established commerce platforms; verify supplier, margin, policy and API assumptions before catalog publication.",
        "success": [
            "Platform economics",
            "Supplier evidence",
            "Margin assumptions",
            "Publication approval",
        ],
    },
]
